spring.application.name=todowebapp
#server.port=8081
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
#logging.level.org.springframework=debug
logging.level.org.springframework=info
logging.level.com.areth.springboot.todowebapp=debug