spring.application.name=todowebapp
#server.port=8081
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
#logging.level.org.springframework=debug
logging.level.org.springframework=info
logging.level.com.areth.springboot.todowebapp=debug

#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

spring.mvc.format.date=yyyy-MM-dd

spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
